/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package karyawan;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author KEVIN_E15
 */
public class Data extends javax.swing.JFrame {

    private static int execute(String SQL) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    private Connection con;
    private Statement stat;
    private ResultSet res;
    private String t;
    private Karyawan[] k;
    public String Nama;
    public int Umur;
    public int Gaji;
    public int BanyakData;
    public String Kondisi;
    /**
     * Creates new form Data
     */
    public Data() {
        initComponents();
        koneksi();
        Data();
    }
    private void koneksi(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost/datakaryawan", "root", "");
            stat=con.createStatement();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    public void SetBatas(int jumlahKaryawan){
        k = new Karyawan[jumlahKaryawan];
    }
    public void SetKaryawan(int indekske, Karyawan karyawan){
        k[indekske] = karyawan;
    }
    public Karyawan AmbilKaryawan(int indekske){
        return k[indekske];
    }
    public void BubbleSort(){
        for(int b = 0; b<BanyakData;b++){
            for(int a = 0; a<BanyakData-1-b; a++){
                if(AmbilKaryawan(a).Gaji < AmbilKaryawan(a+1).Gaji){
                    int g = AmbilKaryawan(a+1).Gaji;
                    int h = AmbilKaryawan(a+1).Umur;
                    String i = AmbilKaryawan(a+1).Nama;
                    AmbilKaryawan(a+1).Gaji = AmbilKaryawan(a).Gaji;
                    AmbilKaryawan(a+1).Umur = AmbilKaryawan(a).Umur;
                    AmbilKaryawan(a+1).Nama = AmbilKaryawan(a).Nama;
                    AmbilKaryawan(a).Gaji = g;
                    AmbilKaryawan(a).Umur = h;
                    AmbilKaryawan(a).Nama = i;
                }
            }
        }
    }
    
    private void Data(){
        CekData();
        SetBatas(BanyakData);
        DefaultTableModel t= new DefaultTableModel();
            t.addColumn("Nama");
            t.addColumn("Umur");
            t.addColumn("Gaji");
        tabel.setModel(t);
        try{
            int a=0;
            res=stat.executeQuery("select * from karyawan");
            while(res.next()){
                Nama = res.getString("nama");
                Umur = res.getInt("umur");
                Gaji = res.getInt("gaji");
                SetKaryawan(a, new Karyawan(Nama, Umur, Gaji));
                a++;
            }
            if(Kondisi == "Urut"){
                BubbleSort();
            }
            for(a = 0; a<BanyakData; a++){
                t.addRow(new Object[]{
                    AmbilKaryawan(a).Nama,
                    AmbilKaryawan(a).Umur,
                    AmbilKaryawan(a).Gaji,
                });
            }
        }catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    
    public void CekData(){
        BanyakData=0;
        try{
            res=stat.executeQuery("select * from karyawan");
            while(res.next()){
                res.getString(1);
                BanyakData++;
            }
        }catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        urut = new javax.swing.JButton();
        normal = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Data Karyawan");

        urut.setText("URUT");
        urut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urutActionPerformed(evt);
            }
        });

        normal.setText("NORMAL");
        normal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                normalActionPerformed(evt);
            }
        });

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nama", "Umur", "Gaji"
            }
        ));
        jScrollPane1.setViewportView(tabel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(urut)
                        .addGap(119, 119, 119))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(normal)
                .addGap(87, 87, 87))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(urut)
                    .addComponent(normal))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void urutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urutActionPerformed
        // TODO add your handling code here:
        Kondisi="Urut";
        Data();
    }//GEN-LAST:event_urutActionPerformed

    private void normalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_normalActionPerformed
        // TODO add your handling code here:
        Kondisi="Normal";
        Data();
    }//GEN-LAST:event_normalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Data().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton normal;
    private javax.swing.JTable tabel;
    private javax.swing.JButton urut;
    // End of variables declaration//GEN-END:variables
}
